default: --format pretty
html_report: --format pretty --format html --out=test_results.html

appium: DRIVER=ios PLATFORM_VERSION=12 DEVICE_NAME="iPhone XS"

# https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/mobile-web.md
# ios_webkit_debug_proxy -c 7f29f76b69e822834077ce10afd24a72a11d7cdd:27753